Release v0.3.2

diff --git a/chloroscan/workflow/Snakefile b/chloroscan/workflow/Snakefile
--- a/chloroscan/workflow/Snakefile
+++ b/chloroscan/workflow/Snakefile
@@ -51,9 +51,9 @@ BINNY_RUNTIME_MANTIS_CFG = BINNY_RUNTIME_DIR / "binny_mantis.cfg"
 BINNY_NLTK_READY = BINNY_RUNTIME_DIR / "nltk.ready"
 BINNY_NLTK_DIR = BINNY_RUNTIME_DIR / "nltk_data"
 
-BINNY_DB_ROOT = BINNY_DIR / "resources"
-BINNY_DB_DIR = BINNY_DB_ROOT / "A2K_database" 
-BINNY_DB_SENTINEL = BINNY_DB_DIR / "hmms" / "merged_hmms" / "merged_hmms.hmm"
+# BINNY_DB_ROOT = BINNY_DIR / "resources"
+BINNY_DB_DIR = config['binning']['database'] # it must be provided.
+BINNY_DB_SENTINEL = BINNY_DB_DIR / "hmms" / "markers" / "markers.hmm"
 
 # Some configs are new for binny, add to snk.yml.
 BINNY_CONFIG = {
@@ -263,38 +263,37 @@ if not DEPTH_FILE_EXISTS:
             "{params.script_dir}/merge_contig_depth.sh"
 
 # declare binny as a module, no longer use separate snakemake anymore.
-rule ensure_binny_database:
-    output:
-        sentinel=BINNY_DB_SENTINEL
-    params:
-        db_root=BINNY_DB_ROOT,
-        article_id="31989147",
-        token="~/.figshare/token"
-    conda:
-        "envs/prepare_binny_db.yml"
-    log:
-        OUTPUT_DIR / "logging_info" / "binny_database_download.log"
-    shell:
-        r"""
-        set -euo pipefail
+# rule ensure_binny_database:
+#     output:
+#         sentinel=BINNY_DB_SENTINEL
+#     params:
+#         db_root=BINNY_DB_ROOT,
+#         article_id="32121661",
+#         token="~/.figshare/token"
+#     conda:
+#         "envs/prepare_binny_db.yml"
+#     log:
+#         OUTPUT_DIR / "logging_info" / "binny_database_download.log"
+#     shell:
+#         r"""
+#         set -euo pipefail
 
-        if [ ! -f {params.token} ]; then
-            echo "Figshare token file not found at {params.token}. Please create your own figshare account and create a file containing your Figshare token at this location."
-            exit 1
-        fi
+#         if [ ! -f {params.token} ]; then
+#             echo "Figshare token file not found at {params.token}. Please create your own figshare account and create a file containing your Figshare token at this location."
+#             exit 1
+#         fi
 
-        mkdir -p {params.db_root}/A2K_database
+#         mkdir -p {params.db_root}/A2K_database
 
-        if [ -s {output.sentinel} ]; then
-            echo "Binny database already present at {params.db_root}/A2K_database" >> {log}
-            exit 0
-        fi
+#         if [ -s {output.sentinel} ]; then
+#             echo "Binny database already present at {params.db_root}/A2K_database" >> {log}
+#             exit 0
+#         fi
 
-        figshare download {params.article_id} -o {params.db_root}/A2K_database >> {log} 2>&1
-        mkdir -p {params.db_root}/A2K_database/pfam
-        mv {params.db_root}/A2K_database/tigrfam2pfam.tsv {params.db_root}/A2K_database/pfam/
-        touch {output.sentinel}
-        """
+#         figshare download {params.article_id} -o {params.db_root}/A2K_database >> {log} 2>&1
+        
+#         touch {output.sentinel}
+#         """
 
 rule prepare_binny_mantis_cfg:
     input:
